# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpBa2zIgxPI7HYZHZZf1R2D-GPPp1CGK
"""

class CustomList:
    def __init__(self):
        self.elements = []  # Stores the actual list elements
        self.counts = {}    # Tracks how many times each element has been added

    def add(self, element):
        self.elements.append(element)
        if element in self.counts:
            self.counts[element] += 1
        else:
            self.counts[element] = 1

    def remove(self, element):
        if element in self.elements:
            self.elements.remove(element)
        else:
            print(f"Element {element} not found in the list.")

    def get_count(self, element):
        return self.counts.get(element, 0)

    def __str__(self):
        return f"List: {self.elements}, Counts: {self.counts}"


# Example Usage
cl = CustomList()
cl.add(10)
cl.add(20)
cl.add(10)
print(cl)  # Output: List: [10, 20, 10], Counts: {10: 2, 20: 1}
cl.remove(10)
print(cl)  # Output: List: [20, 10], Counts: {10: 2, 20: 1}
print(cl.get_count(10))  # Output: 2